CREATE DATABASE QL_KhachSan;
GO
USE QL_KhachSan;
GO

CREATE TABLE LOAIPHONG (
    MaLoai VARCHAR(10) NOT NULL,
    TenLoai NVARCHAR(50) NOT NULL,
    GiaCoBan DECIMAL(18, 2) NOT NULL,
    CONSTRAINT pk_LOAIPHONG PRIMARY KEY (MaLoai)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    VaiTro NVARCHAR(50) NOT NULL, 
    CONSTRAINT pk_NHANVIEN PRIMARY KEY (MaNV)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(100),
    CCCD VARCHAR(20) NOT NULL,
    CONSTRAINT pk_KHACHHANG PRIMARY KEY (MaKH)
);

CREATE TABLE PHONG (
    MaPhong VARCHAR(10) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    SoPhong VARCHAR(10) NOT NULL,
    CONSTRAINT pk_PHONG PRIMARY KEY (MaPhong),
    CONSTRAINT fk_PHONG_LOAIPHONG FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai)
);

CREATE TABLE DATPHONG (
    MaDatPhong VARCHAR(10) NOT NULL,
    MaKH VARCHAR(10) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    TongTien DECIMAL(18, 2) NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    TrangThai NVARCHAR(50) NOT NULL, 
    Version INT DEFAULT 1 NOT NULL,
    CONSTRAINT pk_DATPHONG PRIMARY KEY (MaDatPhong),
    CONSTRAINT fk_DATPHONG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT fk_DATPHONG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE PHONG_NGAY (
    MaPhong VARCHAR(10) NOT NULL,
    Ngay DATE NOT NULL,
    MaDatPhong VARCHAR(10),
    CONSTRAINT pk_PHONG_NGAY PRIMARY KEY (MaPhong, Ngay),
    CONSTRAINT fk_PHONGNGAY_PHONG FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    CONSTRAINT fk_PHONGNGAY_DATPHONG FOREIGN KEY (MaDatPhong) REFERENCES DATPHONG(MaDatPhong)
);

CREATE TABLE THANHTOAN (
    MaGD VARCHAR(10) NOT NULL,
    MaDatPhong VARCHAR(10) NOT NULL,
    SoTien DECIMAL(18, 2) NOT NULL,
    LoaiGiaoDich NVARCHAR(50) NOT NULL, 
    NgayGD DATETIME DEFAULT GETDATE(),
    CONSTRAINT pk_THANHTOAN PRIMARY KEY (MaGD),
    CONSTRAINT fk_THANHTOAN_DATPHONG FOREIGN KEY (MaDatPhong) REFERENCES DATPHONG(MaDatPhong)
);

CREATE TABLE DANHSACHCHO (
    MaWaitlist INT IDENTITY(1,1) NOT NULL, 
    MaKH VARCHAR(10) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    NgayMongMuon DATE NOT NULL,
    TrangThai NVARCHAR(50) DEFAULT N'Đang chờ', 
    CONSTRAINT pk_DANHSACHCHO PRIMARY KEY (MaWaitlist),
    CONSTRAINT fk_WAITLIST_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT fk_WAITLIST_LOAIPHONG FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai)
);